name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 2 * * *' # run at 2 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install
        run: composer install

      # update kirby to latest release of version 4 (includes release candidates!)
      # https://semver.mwl.be/#!?package=getkirby%2Fcms&version=4.*&minimum-stability=RC
      - name: Update Kirby Core
        run: composer require getkirby/cms:"4.*@RC"

      - name: Run Tests
        run: composer test
